import { StyleSheet } from 'react-native';

import {
  colors,
  hairlineWidth,
  radius,
  shadowStyles,
  spacing,
  typography,
} from '@/design-system';

import type { CardStatus, StatusTheme } from './StatusCard.types';

export const statusTheme: Record<CardStatus, StatusTheme> = {
  disabled: {
    accent: colors.danger,
    background: colors.dangerSoft,
    badgeBackground: colors.dangerSoft,
    icon: '!',
    toneLabel: 'blocked',
  },
  enabled: {
    accent: colors.success,
    background: colors.successSoft,
    badgeBackground: colors.successSoft,
    icon: '✓',
    toneLabel: 'active',
  },
  paused: {
    accent: colors.warning,
    background: colors.warningSoft,
    badgeBackground: colors.warningSoft,
    icon: '||',
    toneLabel: 'paused',
  },
  resumed: {
    accent: colors.info,
    background: colors.infoSoft,
    badgeBackground: colors.infoSoft,
    icon: '>',
    toneLabel: 'resumed',
  },
};

export const styles = StyleSheet.create({
  shell: {
    gap: spacing.lg,
  },
  card: {
    ...shadowStyles.card,
    borderCurve: 'continuous',
    borderLeftWidth: 6,
    borderRadius: radius.lg,
    gap: spacing.lg,
    padding: spacing.xl,
  },
  topRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  titleBlock: {
    flex: 1,
    gap: spacing.xs,
    minWidth: 220,
  },
  eyebrow: {
    color: colors.textSubtle,
    fontFamily: typography.bodyFamily,
    fontSize: 13,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  planName: {
    color: colors.ink,
    fontFamily: typography.titleFamily,
    fontSize: 28,
    fontWeight: '700',
  },
  cardSubtitle: {
    color: colors.textMuted,
    fontFamily: typography.bodyFamily,
    fontSize: 16,
    lineHeight: 22,
  },
  statusBadge: {
    alignItems: 'center',
    borderCurve: 'continuous',
    borderRadius: radius.pill,
    flexDirection: 'row',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  statusBadgeIcon: {
    alignItems: 'center',
    borderCurve: 'continuous',
    borderRadius: radius.pill,
    height: 18,
    justifyContent: 'center',
    width: 18,
  },
  statusBadgeIconLabel: {
    color: colors.surface,
    fontFamily: typography.bodyFamily,
    fontSize: 11,
    fontWeight: '800',
    lineHeight: 14,
  },
  statusLabel: {
    fontFamily: typography.bodyFamily,
    fontSize: 13,
    fontWeight: '700',
  },
  accountPreview: {
    backgroundColor: colors.fill,
    borderCurve: 'continuous',
    borderRadius: radius.md,
    gap: spacing.sm,
    padding: spacing.lg,
  },
  accountPreviewTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
  },
  statusIconTile: {
    alignItems: 'center',
    borderCurve: 'continuous',
    borderRadius: radius.md,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  statusIconTileLabel: {
    color: colors.surface,
    fontFamily: typography.bodyFamily,
    fontSize: 17,
    fontWeight: '900',
  },
  accountNumberBlock: {
    flex: 1,
    gap: 2,
  },
  maskedNumber: {
    color: colors.ink,
    fontFamily: typography.bodyFamily,
    fontSize: 21,
    fontWeight: '700',
    letterSpacing: 1.4,
  },
  accountMeta: {
    color: colors.textSubtle,
    fontFamily: typography.bodyFamily,
    fontSize: 13,
    fontWeight: '600',
  },
  statusDescription: {
    color: colors.text,
    fontFamily: typography.bodyFamily,
    fontSize: 15,
    lineHeight: 22,
  },
  detailsCard: {
    backgroundColor: colors.surface,
    borderCurve: 'continuous',
    borderRadius: radius.md,
    overflow: 'hidden',
  },
  detailRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
  },
  detailRowBorder: {
    borderBottomColor: colors.line,
    borderBottomWidth: hairlineWidth,
  },
  detailLabel: {
    color: colors.textMuted,
    flex: 1,
    fontFamily: typography.bodyFamily,
    fontSize: 15,
  },
  detailValue: {
    color: colors.ink,
    flexShrink: 1,
    fontFamily: typography.bodyFamily,
    fontSize: 15,
    fontWeight: '600',
    textAlign: 'right',
  },
  capabilitiesCard: {
    backgroundColor: colors.surface,
    borderCurve: 'continuous',
    borderRadius: radius.md,
    overflow: 'hidden',
    paddingTop: spacing.md,
  },
  sectionLabel: {
    color: colors.textSubtle,
    fontFamily: typography.bodyFamily,
    fontSize: 13,
    fontWeight: '600',
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.sm,
    textTransform: 'uppercase',
  },
  featureRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
  },
  featureRowBorder: {
    borderBottomColor: colors.line,
    borderBottomWidth: hairlineWidth,
  },
  featureDot: {
    backgroundColor: colors.brand,
    borderCurve: 'continuous',
    borderRadius: radius.pill,
    height: 7,
    width: 7,
  },
  featureLabel: {
    color: colors.text,
    fontFamily: typography.bodyFamily,
    fontSize: 15,
  },
  actionPanel: {
    ...shadowStyles.soft,
    backgroundColor: colors.surfaceElevated,
    borderCurve: 'continuous',
    borderRadius: radius.lg,
    gap: spacing.md,
    padding: spacing.lg,
  },
  actionPanelTitle: {
    color: colors.textSubtle,
    fontFamily: typography.bodyFamily,
    fontSize: 13,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  linkButton: {
    alignSelf: 'flex-start',
    paddingVertical: spacing.xs,
  },
  linkButtonLabel: {
    color: colors.brandDeep,
    fontFamily: typography.bodyFamily,
    fontSize: 16,
    fontWeight: '600',
  },
  actionHint: {
    color: colors.textMuted,
    fontFamily: typography.bodyFamily,
    fontSize: 13,
    lineHeight: 19,
  },
  androidSheetOverlay: {
    backgroundColor: colors.scrim,
    flex: 1,
    justifyContent: 'flex-end',
  },
  androidSheet: {
    backgroundColor: colors.surfaceElevated,
    borderTopLeftRadius: radius.lg,
    borderTopRightRadius: radius.lg,
    elevation: 6,
    gap: spacing.lg,
    paddingBottom: spacing.xl,
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.lg,
  },
  androidSheetHandle: {
    alignSelf: 'center',
    backgroundColor: colors.line,
    borderRadius: radius.pill,
    height: 4,
    width: 42,
  },
  androidSheetTitle: {
    color: colors.ink,
    fontFamily: typography.titleFamily,
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: 0,
  },
  androidSheetOption: {
    alignItems: 'center',
    borderColor: colors.line,
    borderRadius: radius.md,
    borderWidth: hairlineWidth,
    flexDirection: 'row',
    gap: spacing.md,
    minHeight: 64,
    overflow: 'hidden',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  androidSheetOptionActive: {
    backgroundColor: colors.brandSoft,
    borderColor: colors.brand,
    borderWidth: 1,
  },
  androidSheetIcon: {
    alignItems: 'center',
    borderRadius: radius.md,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  androidSheetIconLabel: {
    color: colors.surface,
    fontFamily: typography.bodyFamily,
    fontSize: 15,
    fontWeight: '900',
  },
  androidSheetTextBlock: {
    flex: 1,
    gap: 2,
  },
  androidSheetOptionTitle: {
    color: colors.ink,
    fontFamily: typography.bodyFamily,
    fontSize: 16,
    fontWeight: '800',
  },
  androidSheetOptionDescription: {
    color: colors.textMuted,
    fontFamily: typography.bodyFamily,
    fontSize: 13,
    lineHeight: 18,
  },
  androidSheetCheck: {
    color: colors.brand,
    fontFamily: typography.bodyFamily,
    fontSize: 20,
    fontWeight: '900',
    width: 24,
  },
});
