import { StyleSheet } from 'react-native';

import {
  colors,
  hairlineWidth,
  radius,
  shadowStyles,
  spacing,
  typography,
} from '@/design-system';

export const styles = StyleSheet.create({
  safeArea: {
    backgroundColor: colors.background,
    flex: 1,
  },
  screen: {
    flex: 1,
  },
  scrollContent: {
    gap: spacing.lg,
    paddingBottom: spacing.xl,
    paddingHorizontal: spacing.lg,
  },
  header: {
    backgroundColor: colors.brand,
    gap: spacing.md,
    marginHorizontal: -spacing.lg,
    overflow: 'hidden',
    paddingBottom: 76,
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.lg,
  },
  headerIOS: {
    borderBottomLeftRadius: radius.xl,
    borderBottomRightRadius: radius.xl,
  },
  headerAndroid: {
    borderBottomLeftRadius: radius.lg,
    borderBottomRightRadius: radius.lg,
    paddingBottom: 68,
    paddingTop: spacing.xl,
  },
  headerTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  headerShapeLarge: {
    backgroundColor: colors.heroOverlay,
    borderRadius: 120,
    height: 190,
    position: 'absolute',
    right: -36,
    top: -64,
    width: 190,
  },
  headerShapeSmall: {
    backgroundColor: colors.heroOverlay,
    borderRadius: 86,
    bottom: -42,
    height: 132,
    left: -38,
    position: 'absolute',
    width: 132,
  },
  heroEyebrow: {
    color: colors.surface,
    fontFamily: typography.bodyFamily,
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  eyebrow: {
    color: colors.textSubtle,
    fontFamily: typography.bodyFamily,
    fontSize: 13,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  largeTitle: {
    color: colors.surface,
    fontFamily: typography.titleFamily,
    fontSize: 36,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 40,
  },
  subtitle: {
    color: colors.surface,
    fontFamily: typography.bodyFamily,
    fontSize: 17,
    lineHeight: 24,
    maxWidth: 580,
    opacity: 0.92,
  },
  stepperCard: {
    ...shadowStyles.soft,
    backgroundColor: colors.surfaceElevated,
    borderCurve: 'continuous',
    borderRadius: radius.lg,
    gap: spacing.lg,
    marginTop: -58,
    padding: spacing.lg,
  },
  stepperHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sectionEyebrow: {
    color: colors.textSubtle,
    fontFamily: typography.bodyFamily,
    fontSize: 13,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  sectionMeta: {
    color: colors.textMuted,
    fontFamily: typography.bodyFamily,
    fontSize: 13,
    fontWeight: '500',
  },
  animatedContent: {
    gap: spacing.lg,
  },
  footer: {
    backgroundColor: colors.background,
    paddingBottom: spacing.lg,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
  },
  footerTray: {
    ...shadowStyles.soft,
    alignItems: 'center',
    backgroundColor: colors.surfaceElevated,
    borderColor: colors.line,
    borderCurve: 'continuous',
    borderRadius: radius.lg,
    borderWidth: hairlineWidth,
    flexDirection: 'row',
    gap: spacing.sm,
    padding: spacing.sm,
  },
  footerAndroid: {
    alignItems: 'center',
    backgroundColor: colors.surfaceElevated,
    borderTopColor: colors.line,
    borderTopWidth: hairlineWidth,
    flexDirection: 'row',
    gap: spacing.md,
    paddingBottom: spacing.lg,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
  },
  backButton: {
    alignItems: 'center',
    borderCurve: 'continuous',
    borderRadius: radius.md,
    flexDirection: 'row',
    gap: 2,
    justifyContent: 'center',
    minHeight: 50,
    paddingHorizontal: spacing.md,
    width: 108,
  },
  backButtonDisabled: {
    opacity: 0.45,
  },
  backButtonPressed: {
    backgroundColor: colors.fill,
  },
  backChevron: {
    color: colors.brand,
    fontFamily: typography.bodyFamily,
    fontSize: 24,
    fontWeight: '400',
    lineHeight: 24,
    marginTop: -2,
  },
  backButtonLabel: {
    color: colors.brand,
    fontFamily: typography.bodyFamily,
    fontSize: 16,
    fontWeight: '600',
  },
  androidBackButton: {
    alignItems: 'center',
    borderRadius: radius.md,
    justifyContent: 'center',
    minHeight: 48,
    minWidth: 104,
    overflow: 'hidden',
    paddingHorizontal: spacing.lg,
  },
  androidBackButtonLabel: {
    color: colors.brandDeep,
    fontFamily: typography.bodyFamily,
    fontSize: 15,
    fontWeight: '700',
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  backTextDisabled: {
    color: colors.textMuted,
  },
  primaryNavButton: {
    alignItems: 'center',
    backgroundColor: colors.brand,
    borderCurve: 'continuous',
    borderRadius: radius.md,
    flex: 1,
    justifyContent: 'center',
    minHeight: 50,
    paddingHorizontal: spacing.xl,
  },
  androidPrimaryButton: {
    alignItems: 'center',
    backgroundColor: colors.brand,
    borderRadius: radius.md,
    elevation: 3,
    flex: 1,
    justifyContent: 'center',
    minHeight: 52,
    overflow: 'hidden',
    paddingHorizontal: spacing.xl,
  },
  primaryNavButtonPressed: {
    opacity: 0.92,
    transform: [{ scale: 0.99 }],
  },
  primaryNavButtonLabel: {
    color: colors.surfaceElevated,
    fontFamily: typography.bodyFamily,
    fontSize: 17,
    fontWeight: '600',
    textAlign: 'center',
  },
});
